language: scala

env:
  matrix:
    - TRAVIS_JDK=adopt@1.8.202-08

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "$TRAVIS_JDK" && jabba use $_ && java -Xmx32m -version

jobs:
  include:
    - stage: check
      script: sbt headerCheck
      name: "Copyright header check"

    - stage: test
      script: sbt test
      name: "Compile, test and build docs with JDK8"

    - script: sbt test
      name: "Compile, test and build docs with JDK11"
      env: TRAVIS_JDK=adopt@1.11.0-2

    - stage: publish
      script: sbt ci-release
      name: "Cross publish artifacts"

stages:
  # runs on master commits and PRs
  - name: check

  # runs on master commits and PRs
  - name: test

  # runs on main repo version-tagged commits
  - name: publish
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    on_success: never

